
 
记录时间：2018-03-06 09:28:01,908 
线程ID:[10] 
日志级别：  ERROR 
错误描述：引发类型为“Economicalleague.Infrastructure.ProjectException.ResponseContextException”的异常。
 
Economicalleague.Infrastructure.ProjectException.ResponseContextException: 引发类型为“Economicalleague.Infrastructure.ProjectException.ResponseContextException”的异常。
   在 Economicalleague.Services.BaseService.ThrowResponseContextException(ErrCode errCode, String msg) 位置 D:\WorkProject\Economicalleague\Economicalleague.Services\BaseService.cs:行号 20
   在 Economicalleague.Services.Customer.CustomerSrv.Login(LoginInfo loginInfo, String& token) 位置 D:\WorkProject\Economicalleague\Economicalleague.Services\Customer\CustomerSrv.cs:行号 127

 
记录时间：2018-03-06 09:32:25,216 
线程ID:[10] 
日志级别：  ERROR 
错误描述：引发类型为“Economicalleague.Infrastructure.ProjectException.ResponseContextException”的异常。
 
Economicalleague.Infrastructure.ProjectException.ResponseContextException: 引发类型为“Economicalleague.Infrastructure.ProjectException.ResponseContextException”的异常。
   在 Economicalleague.Services.BaseService.ThrowResponseContextException(ErrCode errCode, String msg) 位置 D:\WorkProject\Economicalleague\Economicalleague.Services\BaseService.cs:行号 20
   在 Economicalleague.Services.Customer.CustomerSrv.Login(LoginInfo loginInfo, String& token) 位置 D:\WorkProject\Economicalleague\Economicalleague.Services\Customer\CustomerSrv.cs:行号 127

 
记录时间：2018-03-06 09:53:09,382 
线程ID:[7] 
日志级别：  ERROR 
错误描述：引发类型为“Economicalleague.Infrastructure.ProjectException.ResponseContextException”的异常。
 
Economicalleague.Infrastructure.ProjectException.ResponseContextException: 引发类型为“Economicalleague.Infrastructure.ProjectException.ResponseContextException”的异常。
   在 Economicalleague.Services.BaseService.ThrowResponseContextException(ErrCode errCode, String msg) 位置 D:\WorkProject\Economicalleague\Economicalleague.Services\BaseService.cs:行号 20
   在 Economicalleague.Services.Customer.CustomerSrv.Login(LoginInfo loginInfo, String& token) 位置 D:\WorkProject\Economicalleague\Economicalleague.Services\Customer\CustomerSrv.cs:行号 127

 
记录时间：2018-03-06 09:55:40,480 
线程ID:[7] 
日志级别：  ERROR 
错误描述：127.0.0.1:6379
 
ServiceStack.Redis.RedisException: 127.0.0.1:6379 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:6379
   在 System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
   在 System.Net.Sockets.Socket.Connect(String host, Int32 port)
   在 ServiceStack.Redis.RedisNativeClient.Connect()
   在 ServiceStack.Redis.RedisNativeClient.TryConnectIfNeeded()
   在 ServiceStack.Redis.RedisNativeClient.AssertConnectedSocket()
   --- 内部异常堆栈跟踪的结尾 ---
   在 ServiceStack.Redis.RedisNativeClient.AssertConnectedSocket()
   在 ServiceStack.Redis.RedisNativeClient.AssertServerVersionNumber()
   在 ServiceStack.Redis.RedisClient.GetServerRole()
   在 ServiceStack.Redis.RedisResolver.CreateRedisClient(RedisEndpoint config, Boolean master)
   在 ServiceStack.Redis.RedisResolver.CreateMasterClient(Int32 desiredIndex)
   在 ServiceStack.Redis.PooledRedisClientManager.GetClient()
   在 Economicalleague.Common.RedisHelper.HashSet(String hashId, String key, String value) 位置 D:\WorkProject\Economicalleague\Economicalleague.Common\Helper\RedisHelper.cs:行号 692
   在 Economicalleague.RedisDAL.Customer.TokenRedisDal.GetWXToken(WxLoginInfo val) 位置 D:\WorkProject\Economicalleague\Economicalleague.RedisDAL\Customer\TokenRedisDal.cs:行号 244
   在 Economicalleague.Services.Customer.TokenSrv.GetWXToken(WxLoginInfo val) 位置 D:\WorkProject\Economicalleague\Economicalleague.Services\Customer\TokenSrv.cs:行号 32
   在 Economicalleague.Services.Customer.CustomerSrv.Login(LoginInfo loginInfo, String& token) 位置 D:\WorkProject\Economicalleague\Economicalleague.Services\Customer\CustomerSrv.cs:行号 130

 
记录时间：2018-03-06 09:55:41,401 
线程ID:[7] 
日志级别：  ERROR 
错误描述：ControllerName=CustomerApi,ActionName=Login,Msg=127.0.0.1:6379
 
ServiceStack.Redis.RedisException: 127.0.0.1:6379 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:6379
   在 System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
   在 System.Net.Sockets.Socket.Connect(String host, Int32 port)
   在 ServiceStack.Redis.RedisNativeClient.Connect()
   在 ServiceStack.Redis.RedisNativeClient.TryConnectIfNeeded()
   在 ServiceStack.Redis.RedisNativeClient.AssertConnectedSocket()
   --- 内部异常堆栈跟踪的结尾 ---
   在 ServiceStack.Redis.RedisNativeClient.AssertConnectedSocket()
   在 ServiceStack.Redis.RedisNativeClient.AssertServerVersionNumber()
   在 ServiceStack.Redis.RedisClient.GetServerRole()
   在 ServiceStack.Redis.RedisResolver.CreateRedisClient(RedisEndpoint config, Boolean master)
   在 ServiceStack.Redis.RedisResolver.CreateMasterClient(Int32 desiredIndex)
   在 ServiceStack.Redis.PooledRedisClientManager.GetClient()
   在 Economicalleague.Common.RedisHelper.HashSet(String hashId, String key, String value) 位置 D:\WorkProject\Economicalleague\Economicalleague.Common\Helper\RedisHelper.cs:行号 692
   在 Economicalleague.RedisDAL.Customer.TokenRedisDal.GetWXToken(WxLoginInfo val) 位置 D:\WorkProject\Economicalleague\Economicalleague.RedisDAL\Customer\TokenRedisDal.cs:行号 244
   在 Economicalleague.Services.Customer.TokenSrv.GetWXToken(WxLoginInfo val) 位置 D:\WorkProject\Economicalleague\Economicalleague.Services\Customer\TokenSrv.cs:行号 32
   在 Economicalleague.Services.Customer.CustomerSrv.Login(LoginInfo loginInfo, String& token) 位置 D:\WorkProject\Economicalleague\Economicalleague.Services\Customer\CustomerSrv.cs:行号 150
   在 Economicalleague.Api.Controllers.Api.CustomerApiController.Login(RequestContext`1 req) 位置 D:\WorkProject\Economicalleague\Economicalleague.Api\Controllers\Api\CustomerApiController.cs:行号 68
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()

 
记录时间：2018-03-06 09:56:00,255 
线程ID:[9] 
日志级别：  ERROR 
错误描述：引发类型为“Economicalleague.Infrastructure.ProjectException.ResponseContextException”的异常。
 
Economicalleague.Infrastructure.ProjectException.ResponseContextException: 引发类型为“Economicalleague.Infrastructure.ProjectException.ResponseContextException”的异常。
   在 Economicalleague.Services.BaseService.ThrowResponseContextException(ErrCode errCode, String msg) 位置 D:\WorkProject\Economicalleague\Economicalleague.Services\BaseService.cs:行号 20
   在 Economicalleague.Services.Customer.CustomerSrv.Login(LoginInfo loginInfo, String& token) 位置 D:\WorkProject\Economicalleague\Economicalleague.Services\Customer\CustomerSrv.cs:行号 127

 
记录时间：2018-03-06 09:57:33,286 
线程ID:[7] 
日志级别：  ERROR 
错误描述：引发类型为“Economicalleague.Infrastructure.ProjectException.ResponseContextException”的异常。
 
Economicalleague.Infrastructure.ProjectException.ResponseContextException: 引发类型为“Economicalleague.Infrastructure.ProjectException.ResponseContextException”的异常。
   在 Economicalleague.Services.BaseService.ThrowResponseContextException(ErrCode errCode, String msg) 位置 D:\WorkProject\Economicalleague\Economicalleague.Services\BaseService.cs:行号 20
   在 Economicalleague.Services.Customer.CustomerSrv.Login(LoginInfo loginInfo, String& token) 位置 D:\WorkProject\Economicalleague\Economicalleague.Services\Customer\CustomerSrv.cs:行号 127
